# Generated by Django 4.2.11 on 2026-05-23 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte')], max_length=5)),
                ('document_number', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Masculino'), ('FEMALE', 'Femenino')], max_length=20)),
                ('grade', models.CharField(choices=[('Preescolar', 'Preescolar'), ('1°', 'Primero'), ('2°', 'Segundo'), ('3°', 'Tercero'), ('4°', 'Cuarto'), ('5°', 'Quinto'), ('6°', 'Sexto'), ('7°', 'Séptimo'), ('8°', 'Octavo'), ('9°', 'Noveno'), ('10°', 'Décimo'), ('11°', 'Undécimo')], max_length=20)),
                ('section', models.CharField(blank=True, max_length=5, null=True)),
                ('guardian_name', models.CharField(max_length=150)),
                ('guardian_phone', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('consent_date', models.DateTimeField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('socioeconomic_stratum', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'students',
                'indexes': [models.Index(fields=['is_active'], name='students_is_acti_4aecc9_idx'), models.Index(fields=['first_name', 'last_name'], name='students_first_n_ce3d36_idx')],
            },
        ),
    ]
