# Generated by Django 4.2.11 on 2026-05-23 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PHYSICAL_DISABILITY', 'Discapacidad Física'), ('SENSORY_VISUAL', 'Discapacidad Sensorial Visual'), ('SENSORY_AUDITORY', 'Discapacidad Sensorial Auditiva'), ('COGNITIVE_DISABILITY', 'Discapacidad Cognitiva'), ('PSYCHOSOCIAL_DISABILITY', 'Discapacidad Psicosocial'), ('MULTIPLE_DISABILITY', 'Discapacidad Múltiple'), ('SPECIFIC_LEARNING_DISORDER', 'Trastorno Específico del Aprendizaje'), ('ADHD', 'TDAH'), ('AUTISM_SPECTRUM', 'Trastorno del Espectro Autista (TEA)'), ('GIFTEDNESS', 'Superdotación')], max_length=50)),
                ('description', models.TextField()),
                ('normative_reference', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Diagnóstico del Catálogo',
                'verbose_name_plural': 'Diagnósticos del Catálogo',
                'db_table': 'diagnostic_catalog',
                'indexes': [models.Index(fields=['name'], name='diagnostic__name_e0db9f_idx'), models.Index(fields=['is_active'], name='diagnostic__is_acti_7cb293_idx'), models.Index(fields=['category'], name='diagnostic__categor_e5ee0a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CharacterizationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField()),
                ('severity_level', models.CharField(choices=[('MILD', 'Leve'), ('MODERATE', 'Moderado'), ('SEVERE', 'Severo')], max_length=20)),
                ('identification_date', models.DateField()),
                ('observations', models.TextField(blank=True, null=True)),
                ('cognitive_area_notes', models.TextField(blank=True, null=True)),
                ('communicative_area_notes', models.TextField(blank=True, null=True)),
                ('socioemotional_area_notes', models.TextField(blank=True, null=True)),
                ('motor_area_notes', models.TextField(blank=True, null=True)),
                ('sensory_area_notes', models.TextField(blank=True, null=True)),
                ('academic_area_notes', models.TextField(blank=True, null=True)),
                ('behavioral_area_notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diagnostic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='characterizations', to='diagnostics.diagnosticmodel')),
            ],
            options={
                'verbose_name': 'Caracterización',
                'verbose_name_plural': 'Caracterizaciones',
                'db_table': 'characterizations',
                'indexes': [models.Index(fields=['student_id'], name='characteriz_student_a8b146_idx'), models.Index(fields=['is_active'], name='characteriz_is_acti_3b8715_idx'), models.Index(fields=['created_at'], name='characteriz_created_8e5f9e_idx'), models.Index(fields=['student_id', 'is_active'], name='characteriz_student_aa720c_idx')],
            },
        ),
    ]
